// src/lead-pipeline/schemas/zod-schemas.ts
import { z } from 'zod';

/**
 * 1. CLASSIFICATION SCHEMA
 * Evaluates intent and safely extracts core B2B profile indicators + HR/Support data
 */
export const LeadClassificationSchema = z.object({
  // The specific routing category for the automation pipeline (Strict Phase 3 Syllabus)
  category: z.enum(['hot_lead', 'cold_lead', 'support_request', 'hr_screening', 'spam']),
  
  // Model confidence level to catch hallucinations early
  confidence: z.number().min(0).max(1),
  
  // Forces a human in the loop if text is threatening, angry, or complex
  requires_human: z.boolean(),
  
  // Brief explanation of the classification for debugging logs
  reasoning_summary: z.string().max(250),
  
  // Structured extraction fields (All set to nullish to prevent missing-key crashes)
  extracted_data: z.object({
    company_name: z.string().nullish(),
    budget_mentioned: z.string().nullish(),
    project_timeline: z.string().nullish(),
    contact_phone: z.string().nullish(),
    role_applied_for: z.string().nullish(),
  }),
});

/**
 * 2. REPLY DRAFT SCHEMA
 * Governs the auto-response criteria optimized for conversion and corporate communications
 */
export const LeadReplySchema = z.object({
  // The actual text payload generated by the LLM
  draft_reply: z.string().min(10).max(1000),
  
  // Monitors tone matching to ensure consistency across variants
  tone_used: z.enum(['professional', 'enthusiastic', 'warm', 'empathetic']),
  
  // Flag telling n8n exactly which route/department to push this to
  suggested_action: z.enum([
    'book_call', 
    'escalate_to_support', 
    'escalate_to_hr', 
    'escalate_manually', 
    'archive'
  ]),
});

/**
 * 3. JUDGE SCHEMA
 * Used by your secondary model (Groq) to grade the draft quality defensively
 */
export const LeadJudgeSchema = z.object({
  scores: z.object({
    accuracy: z.number().min(0).max(10),       // Did it hallucinate details?
    tone: z.number().min(0).max(10),           // Is it overly aggressive or too passive?
    completeness: z.number().min(0).max(10),   // Did it address customer points?
    safety: z.number().min(0).max(10),         // Is there any false policy promise?
  }),
  overall_score: z.number().min(0).max(10),
  decision: z.enum(['accept', 'edit', 'reject']),
  feedback: z.string(),
});

/**
 * 4. A/B TEST LOG SCHEMA
 * Retained from your previous framework to monitor performance analytics between prompt variations
 */
export const ABTestLogSchema = z.object({
  test_name: z.string(),
  group: z.enum(['A', 'B']),
  prompt_version: z.string(),
  classification_accuracy: z.number().optional(),
  judge_score: z.number().optional(),
  human_escalation: z.boolean(),
  processing_time_ms: z.number(),
});

// Structural Type Exports for compilation type-safety in your services
export type LeadClassification = z.infer<typeof LeadClassificationSchema>;
export type LeadReply = z.infer<typeof LeadReplySchema>;
export type LeadJudgeResult = z.infer<typeof LeadJudgeSchema>;
export type ABTestLog = z.infer<typeof ABTestLogSchema>;